# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5d72e609374ca44aec1f2203fb3e8b5935f1440a74acbc41f3f8a752f8dd231ae2d2fcb426c7950a57b02fb4065237f6d149af181144121216f0e1aebc409c5

test:
  secret_key_base: 5724214b74bdeae320df019ea57ce5463c1a25c4e1733e49ebbb417f9a7021a6461a300ac68fb010ba78d4c3ce7139e1904978b7a10d7ba174a976a1602ade62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
